version: "3.8"
networks:
  roboshop:
    driver: bridge
services:
 web:
  image: vkandula650/web:v1
  container_name: web
  ports:
    - "80:80"
  depends_on:
   - catalogue
   - user
   - mongodb
   - cart
   - shipping
 user:
  image: vkandula650/user:v1
  container_name: user
 catalogue:
  image: vkandula650/catalogue
  container_name: catalogue
  depends_on: 
   - mongodb
 mongodb:
  image: vkandula650/mangodb 
  container_name: mongodb
 Redis:
  image: redis:latest
 cart:
  image: vkandula650/cart:v1
  container_name: cart
  depends_on: 
   - catalogue
   - Redis
 Mysql:
  image: vkandula650/mysql:v1
  container_name: mysql
 shipping:
  image: techworldwithsiva/shipping:k8
  container_name: shipping
  depends_on: 
   - Mysql
 rabbitmq:
  image: rabbitmq
  container_name: rabbitmq
 payment:
  image: vkandula650/payment:v1
  container_name: payment
  depends_on: 
   - rabbitmq
 ratings:
  image: vkandula650/ratings:v1
  container_name: ratings
  depends_on:
   Mysql
